### ISSUE TITLE
Newtek TC1 Switcher

### ISSUE THREAD

**Issue by kaleforge** [bitfocus/companion-module-newtek-tricaster#1]
I would love the same controls that are on the ATEM switcher on the TC1
This switcher is run off of a windows OS

Thank you!

**Comment by JeffreyDavidsz** [comment]
@willosof can you supply a connection to one?

**Comment by JeffreyDavidsz** [comment]
@joniose please test the module against your switcher, it's not 100% complete but the basics are in. Take a look at the build in presets for easy drag and drop

**Comment by joniose** [comment]
As far as I understand I have to recompile Companion, right?
What do I use for this?

Maybe I am not the right person to test the plugin without help. I have a TC1 and a streamdeck here and would like to try some things.

Can you give me a little instruction?

**Comment by JeffreyDavidsz** [comment]
You can download a beta build from the site at bitfocus.io under the stable there is a small link (builds) just pick one off the latest

**Comment by joniose** [comment]
ok thanks :D

**Comment by joniose** [comment]
I've tested today the Module.

- shortcuts are working
- Media Actions are working
- Feedback on Preview ist working
- Feedback on Program is not working
- Feedback on Media Playback is not working
- Button press in PGM, PVW and ME is working

Responsiveness is great
Not seen any other issues

**Comment by JeffreyDavidsz** [comment]
Thanks for your reply, today I rewrote connection so things have changed. I'll need to do some extra testing/adding. I'll close this issue and leave one open as reminder
