### ISSUE TITLE
Emem & Comp variable

### ISSUE THREAD

**Issue by hoechstn** [bitfocus/companion-module-newtek-tricaster#24]
Is there any way we could get Emem & Comp naming variables? These values are constantly changing and it would be nice if companion would follow along.

**Comment by bryce-seifert** [comment]
I don't currently see a way of gathering this info via the API. It's possible it's been added since that documentation was last updated, but I dug a little bit and didn't see it. Might be worth reaching out to NewTek and seeing if they can add it to their API

**Comment by hoechstn** [comment]
I’ll reach out to our technical rep and see what he can gather for us. I’ll report back on what he says regarding that API call

**Comment by hoechstn** [comment]
Currently not supported with API. will keep an eye on updates and open a ticket if support is added in the future.
