### ISSUE TITLE
Connect to Tricaster by name instead of by IP

### ISSUE THREAD

**Issue by jwagg999** [bitfocus/companion-module-newtek-tricaster#26]
For mobile setups that connect to different networks, it would make it easier for non-technical users to connect by netbios name (\\tc-sports) instead of only by IP address.  Is there any chance you could add this ability?

**Comment by bryce-seifert** [comment]
This will be possible with the rewrite for Companion v3 https://github.com/bitfocus/companion-module-newtek-tricaster/commit/68161f8813028a872660c281dce44df844e6184c
