### ISSUE TITLE
Don't have any "actions" available to bind

### ISSUE THREAD

**Issue by Toninom11** [bitfocus/companion-module-newtek-tricaster#29]
Hi,
Maybe I'm missing something but I don't seem to have any option when I add the Tricaster Newtek connections, the "actions" library doesn't load up.
But the Presets are available so I find it kind of weird since the presets themselves are recalling actions that even I cannot see, but they work well,
any idea on how I can fix it? 
(I've tried on companion beta and the problem is still here)
Thanks!

**Comment by bryce-seifert** [comment]
Are there any errors in the companion log?
Do the variables and feedbacks show up properly?

And are you trying to access the actions through the "browse" button, or with the dropdown menu?

**Comment by Toninom11** [comment]
Yes I have one error, the companion can't connect to the Tricaster but it's because I'm using one that is not compatible with LivePanel, but the actions from the presets are still working, and I've tried for other connections I don't even need it to be connected to have access to the actions list.
Yes the variables are visible and the feedbacks only shows when clicking the "browse" button, but I think that it is normal? 

I've tried with both the browse button and the dropdown menu, but the only thing I see is "Internal" but no Tricaster, which is weird because when I bind a preset to a button, I can see that the action of the button is a "Tricaster : xxxxx" but I still can't see any other

Thank you for your time !

**Comment by bryce-seifert** [comment]
I know in v3 it shouldn't show actions, feedback, etc until connected. The thinking here is a lot of the action options are built based on the model being used, so we wait until that's confirmed before binding those.

When you say the "actions from the presets are still working" do you mean they're showing up, or do they actually work with the tricaster? Also what Tricaster are you using?

**Comment by Toninom11** [comment]
Alright that can explain why I can't see them, but it's weird that I can still have access to feedback and variables, maybe it is because when I try to connect, it says connected for .2s et then come back to "not connected".

I mean that when I'm binding the DDR1 PLAY/PAUSE on a button, the play/pause button does work on the Tricaster, even though it doesn't say connected, so it actually works. I'm using a Tricaster TXCD410 running on the update 2-6-200110, and I believe that it is the latest version I can have without having to buy another licence.

**Comment by bryce-seifert** [comment]
Can you provide a readout of what happens when you go to
http://`tricasterip`/v1/version
in a browser?

**Comment by Toninom11** [comment]
I can't seem to reach it, and I'm 100% confident that I'm calling the right IP, I've tried in different browsers but they all can't reach it. 
I tried to do a 'netstat -a' on my Tricaster to try and figure out how can I go in this page, but I can't find any ports that shows any UI when typed in a browser.
But the streamdeck connected to another computer on the same network as my Tricaster can still trigger the DDR via the preset button of the companion
I will try to connect the companion to another Tricaster that has Livepanel, make a config and export it to see if the actions stills works even though it doesn't say "connected", I'll keep you updated
Thanks again for your time !

**Comment by bryce-seifert** [comment]
Got it. So it seems like the /version was likely added in a later Tricaster update than what you have installed.
I'll try to work on a better onboarding process for Tricasters that don't have the version api calll.

**Comment by bryce-seifert** [comment]
https://github.com/bitfocus/companion-module-newtek-tricaster/pull/39 should allow you to at least connect while using an older firmware. I can't promise 100% compatibility, but you should at least be able to see the actions, etc
