### ISSUE TITLE
NewTek Tricaster platform

### ISSUE THREAD

**Issue by JeffreyDavidsz** [bitfocus/companion-module-newtek-tricaster#3]
Support for the Tricaster family switchers

As for what would be good to have:
 All inputs and control of them on preview/program
 Feedback of name of inputs/MEs
 Choosing MEs
 Individual Key/DSK control of each ME
 Tally for anything live
 Beeing able to turn on/off Autoplay/looping etc for VTRs
 Triggering presets on ME layers
 Triggering VTR lists
 Changing Multiviewer presets on the outputs
 Muting/unmuting audio tracks (with feedback)
 Starting/Stopping streaming (with feedback)
 Starting/Stopping recording (with feedback)
 Feedback on the remaining VTR time
 If it is possible, if there is any control over the Apps/Live call connect feature it would be great

**Comment by Moving-Light** [comment]
Just a suggestion.  You can probably integrate part of [Tally Arbiter](https://github.com/josephdadams/TallyArbiter) (already Companion compatible) to get tally data into the module.

**Comment by JeffreyDavidsz** [comment]
Hi what do you mean exactly? These are switchers so they generate tally

**Comment by Moving-Light** [comment]
I was meaning for the `Tally for anything live` line in the original comment.  The code is there to pull tally data from the tricaster into companion for feedback

**Comment by Moving-Light** [comment]
Sorry about that.  I had not looked through the code and I have not tested this out yet so I did not realize you had tally already coded.  My bad.

**Comment by RasterboxOff** [comment]
Hello Jeffrey.
Thank you so much for this module, it literally makes my life easier. I found one issue, though. 
If I try the "Set source to DSK"-Action nothing happens. The TriCaster (a TC1) gives the following feedback in the notifications, no matter which combination of DSK and source I tried, it reads "Shortcut Not Found: undefined_select"
Other shortcuts I tried from the module work nicely.
For now I use the custom shortcut to circumvent this, but I thought I should reach out. 

Here a custom shortcut example for selecting Buffer 10 in DSK 2 in the Main row, for anyone interested/in need: 
`<shortcut><shortcut name="main_dsk2_select_named_input" value="BFR10" /></shortcuts>`

One thing that came to mind, that might fit in the module, would be the possibility to directly send http get commands from there.
`http://TriCasterIP/v1/trigger?name=NAME`

'NAME' being the value that could be set within companion. This way you can trigger any macro within the TriCaster, without the need of using the generic http.

In any case, awesome module! Thank you very much.

Kind ones,
Alex

**Comment by JeffreyDavidsz** [comment]
Thanks, for the message its a typo from my part, fixed it. Also adding the macro option. Found a connection issue which has nothing to do with the module, but want to fix this first and test before I add it to the core

**Comment by RasterboxOff** [comment]
Great News.

Thank you!

Jeffrey Davidsz ***@***.***> schrieb am Fr. 9. Apr. 2021 um
20:20:

**Comment by JeffreyDavidsz** [comment]
`http://TriCasterIP/v1/trigger?name=NAME` doesn't seem to work with system macro's I've tried the `Stream: Start` and `Transition: Take` When putting it in the browser it doesn't work either. Might be the spaces in between. What did you use as name?

**Comment by RasterboxOff** [comment]
I'm not sure if I ever used it with system macros. The trigger doesn't correspond to anything that already exists, as far as I know. The name can be whatever you like it to be. In the macro window you can click in the field of one of the triggers (see picture) and the TriCaster listens for a command. Then you can send whatever NAME you wish to the TriCaster to assign this macro to the message. Once assigned, the macro starts when you send the message again. It works like the DMX/MIDI mapping in Resolume, if that is of any help. I never used spaces in my NAMEs, though. I used names like "BUG1_ON" or "RELOAD_VIDEOS" it can be anything you like. Be sure the check mark in front of the folder and macro name is ticked, otherwise the macros are deactivated.
Hope that helps. 

<img width="461" alt="Bildschirmfoto 2021-04-15 um 20 11 51" src="https://user-images.githubusercontent.com/82218205/114918215-1fd68e00-9e27-11eb-9ae0-167f8e195bdc.png">

**Comment by frankleggett** [comment]
Excuse my ignorance but how do I install this module as it isn't listed inside companion? I have searched the manufacturer and the catergory and I can't find it. I can download the code but how do I manually install the module?

**Comment by RasterboxOff** [comment]
Hey.

You need to install a beta build for this. There is no need to manually
install the module. It might be possible, but I wouldn’t  know how to do
it.
Be aware that the beta builds are not meant for actual show usage. We all
do it, I suppose, but officially you using it at you own risk (like with
every free software tbh.)

**Comment by frankleggett** [comment]
Thanks

**Comment by frankleggett** [comment]
I have installed this from the new Companion build 2.1.3 and from a Beta buid and when I select Tricaster "Set source to Program" I get no sources in the Options list only "0". I have a Tricaster Mini ADV3 Build 7-4 -210311. I get the same for "Set source to Preview", "Set source to DSK" etc.

**Comment by frankleggett** [comment]
Solved. I didn't notice the polling setting needs to be set.

**Comment by RasterboxOff** [comment]
Glad to hear!

**Comment by frankleggett** [comment]
I have problems with the Auto Transition not working then it blocking the Auto Transition from working on the Tricaster GUI as well. Cut seems to be OK. there is no feedback for DDR 1 on the Preview or Program bus.

**Comment by JeffreyDavidsz** [comment]
mmm 
on cut its this: `<shortcuts><shortcut name="main_background_take" /></shortcuts>` 
on auto its this: `<shortcuts><shortcut name="main_background_auto" /></shortcuts>`
So that's not really something I would know how to handle. 

For the feedback I'll check
