### ISSUE TITLE
v3 not seeing custom macros

### ISSUE THREAD

**Issue by middb** [bitfocus/companion-module-newtek-tricaster#32]
Just installed v3 rc1. Companion still triggers existing custom macros, but does not see them correctly (the name is preceded by "??") so they cannot be edited, nor can any new custom macros be added ("no options available"). It sees the system macros though. No error messages in the log file. I reverted to v2 and everything works as expected.

**Comment by bryce-seifert** [comment]
I'm currently able to see custom macros, without the question marks or no options issues.

Is the custom macro issue present across multiple tricaster sessions, or just one in particular? I'm wondering if you create a new session and new macro if it persists.

Are there any errors in the Companion log related to the Tricaster module?

**Comment by middb** [comment]
I just tried a new session, and it sees the custom macros. When I return to the existing session, it now also sees the custom macros--up until I disable/re-enable the Tricaster, after which I get "??" again. The same macros are available across all sessions, and there are no error messages generated. 

I'm not sure what's in the current session (it's relatively new) that could be causing a conflict, especially since it works fine with companion v2.

![Screenshot 2023-06-13 150255](https://github.com/bitfocus/companion-module-newtek-tricaster/assets/135717897/c4e99151-96f4-4f37-8729-83a7a9144f4a)

**Comment by bryce-seifert** [comment]
Very odd indeed.

After encountering the behavior, could you go to the Companion logs page and choose "Export support bundle" and then send that to me? bryceapps@icloud.com

**Comment by bryce-seifert** [comment]
Should be fixed with https://github.com/bitfocus/companion-module-newtek-tricaster/pull/39
