### ISSUE TITLE
Input Variables

### ISSUE THREAD

**Issue by cookdoeyl** [bitfocus/companion-module-newtek-tricaster#38]
Upon booting a TC1, the first time a project is opened, none of the Input Name variables are detected by Companion. If the TC project is closed and re-opened, the variables populate.

**Comment by bryce-seifert** [comment]
Which variables are you referencing specifically? The SourceName ones?

**Comment by cookdoeyl** [comment]
The Input Short Name's used to work. And it actually appears those are no longer functioning at all. index.js line 506 appears to pull it. I can check what version of TC that system is running. Maybe they broke something with an update.

**Comment by bryce-seifert** [comment]
Can you provide the exact variable text from the buttons you're having issues with? is it
`$(tricaster:pgm_source)` and `$(tricaster:pvw_source)`

**Comment by cookdoeyl** [comment]
In my button text, I have "$(tricaster:input2)" to show the Button Text from TC. I have found this variable works in Companion 2.4.2. But not in 3.0.0.
