### ISSUE TITLE
No connection between Companion and Tricaster

### ISSUE THREAD

**Issue by SK-RaoSel** [bitfocus/companion-module-newtek-tricaster#40]
Hi Folks, 

i get this message when i try to connect the Tricaster TC-2-Elite: "error: Unable to connect to Tricaster. Check your device address in the module settings"

IP is set correct. The Live-Panel Password ist turn off. Any Idea?

companion: v3.0.0 - 2023-06-21 (stable)

**Comment by bryce-seifert** [comment]
Can you try the latest beta of Companion?

It includes a fix for https://github.com/bitfocus/companion-module-newtek-tricaster/issues/29 which I think might be a similar issues.

Also, which version of Tricaster firmware are you on? Have you successfully used this module before?

**Comment by bryce-seifert** [comment]
@SK-RaoSel Are you still having this issue? Any more info you can provide? Can you try the latest companion beta?

**Comment by jamesthompson2004** [comment]
I had this same problem when upgrading to TriCaster's August release:  the TriCaster update broke the Companion connection.  Confirmed that Beta 6162 *does* fix the problem on TriCaster Mini 4K.

Thank you for your work on this!  Newtek would only give me an old update back to April of 2022.  Fixing this fixed our workflow.  It was going to be a Very Bad Week.

**Comment by bryce-seifert** [comment]
@jamesthompson2004 Thanks for the confirmation! Sorry it took a bit to get to, I was worried it was going to be a harder fix than it was and my Tricaster was in heavy use. Glad all is working now!
