### ISSUE TITLE
Tricaster Module no longer connecting to Tricaster after Tricater Update

### ISSUE THREAD

**Issue by nixaathletics** [bitfocus/companion-module-newtek-tricaster#41]
Here some screenshots of the issue at hand this was working until I updated the Tricaster.  Now it just timesout and doesn't stay connected.

![Screenshot of Bitfocus Companion - Admin (1)](https://github.com/bitfocus/companion-module-newtek-tricaster/assets/143754776/cde3c82c-2a9d-4d7c-a7ce-c633176e057f)
![Screenshot of Bitfocus Companion - Admin](https://github.com/bitfocus/companion-module-newtek-tricaster/assets/143754776/aaafeba5-de3e-433c-b0d4-e3cdc822ccc0)

**Comment by bryce-seifert** [comment]
Which version of the Tricaster software are you using?

Are there any errors in the companion log?

**Comment by nixaathletics** [comment]
TC1
Build Number: 8-1-230825C

Just updated a few days ago.  



23.08.31 22:27:17 Instance/Wrapper/tricaster: Unable to connect to Tricaster. Check your device address in the module settings
23.08.31 22:27:22 Instance/Wrapper/tricaster: Unable to connect to Tricaster. Check your device address in the module settings
23.08.31 22:28:29 Instance/Wrapper/tricaster: Unable to connect to Tricaster. Check your device address in the module settings

The IP Address has not changed on the Tricaster after the update just will no longer connect.

**Comment by bryce-seifert** [comment]
I don't see anything obvious listed in the release notes.

I'll have to upgrade and test at some point, but don't currently have a unit running that build

**Comment by kaleforge** [comment]
Any update on this?

**Comment by bryce-seifert** [comment]
@kaleforge I'll try to get to it soon, but since I only have one Tricaster and it's been in production use I need to find a decent downtime to upgrade and test.

**Comment by bryce-seifert** [comment]
@nixaathletics @kaleforge I think if you download the latest companion beta this should be fixed. I updated my Tricaster, and it seems they changed some of the XML structure which was causing it to error.

Let me know if this doesn't fix it!

**Comment by kaleforge** [comment]
Just did it! Thank you

**Comment by nixaathletics** [comment]
@bryce-seifert I just updated my Tricaster again after rolling it back to the older verison.  It appears to be working! Thanks for the fix.
