### ISSUE TITLE
Tricaster not connecting time out

### ISSUE THREAD

**Issue by rpotanka** [bitfocus/companion-module-newtek-tricaster#47]
TC2 Build: 8-2-2312274 NDI version. 5.6.0.0
Companion Ver: 3.2.0

Tri caster module times out upon trying to connect. 
![image](https://github.com/bitfocus/companion-module-newtek-tricaster/assets/157146126/5a5cabf8-6c74-4b4f-8e85-dc5d1b0c1fa4)

**Comment by bryce-seifert** [comment]
I have not tested with the latest tricaster firmware version, which is what seems to be in use

Was this previously working before the firmware update?

**Comment by rpotanka** [comment]
We only installed this morning. We had an older version of tricaster firmware(8-0-230405),companion ver 3.1.2, mod v2.0.4. Worked great for about 20-30mins. As we added user macros to actions we started having connection issues. We read that updating tricaster firmware might help. It did not. We then changed companion to version3.2.  That didn't help. Also changed the companion port number to 8099. We the deleted the module and readded. It didn't work. Rebooted companion no luck. Rebooted machine no luck. Was installed wire shark to capture some data and during the wire-shark install the connection works and stayed stable for about a hour then I needed to leave for the day.

**Comment by bryce-seifert** [comment]
Gotcha. I'm betting something with the new firmware is causing issues, this has happened before when Newtek changes parts of the API with a firmware release

The known stable firmware for the Tricaster is 8-1-230825

I'm not sure when I'll have a chance to test with the latest Tricaster firmware, as our unit is in production use. But If you're able to downgrade to  8-1-230825 I'm happy to help troubleshoot any issues with macros, etc

**Comment by rpotanka** [comment]
It seemed to be fine before I left. question about macro naming. Do you know of any limitations when it comes to special characters in names ?   Once the connection reestablished it seemd like macros with &@$ did not execute from bit compainion without renaming. Also any plans for DSK on M/E not just on main ?

**Comment by bryce-seifert** [comment]
I'm not sure why special characters would create issues, but I can look into that.

For DSK, in the very latest beta you should be able to control DSK on different M/Es with "Set DSK On Air"

**Comment by rpotanka** [comment]
you can close this it has been stable all week. I don't know what it was but it works !!
